# Generated by Django 3.2.6 on 2021-10-08 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CAN', 'Cancelado'), ('ACT', 'Activo'), ('FIN', 'Finalizado')], default='PEN', max_length=3)),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_encargado', to=settings.AUTH_USER_MODEL)),
                ('scrum_member', models.ManyToManyField(blank=True, related_name='proyecto_asignado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyectos',
                'ordering': ('-fecha_inicio',),
                'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('cancelar_proyecto', 'Puede cancelar un proyecto en estado pendiente'), ('gestionar_scrum_members', 'Puede Agregar/Quitar Scrum Members de un proyecto'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('gestionar_roles_proyecto', 'Puede Agregar/Asignar/Modificar/Eliminar Roles de un Proyecto'), ('importar_roles_proyecto', 'Puede Importar roles de proyecto'), ('gestionar_user_stories', 'Puede Agregar/Modificar/Eliminar User Stories de un proyecto'), ('iniciar_ppoker_proyecto', 'Puede iniciar planning poker de un sprint'), ('estimar_userstory_proyecto', 'Puede estimar User Stories en el Sprint Backlog'), ('cargar_sprint_backlog_proyecto', 'Puede cargar User Stories en el Sprint Backlog'), ('estimar_sprint', 'Puede estimar sprint')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_desarrollo', models.DateTimeField(blank=True, null=True)),
                ('duracion_estimada_dias', models.IntegerField(blank=True, null=True)),
                ('horas_realizadas', models.FloatField(blank=True, default=0, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('conf1', 'Carga de Sprint Backlog'), ('conf2', 'Planning Poker'), ('conf3', 'Ultimas Configuraciones'), ('en_desarrollo', 'Sprint en desarrollo')], default='conf1', max_length=20)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_sprints', to='projectmanager.proyecto')),
                ('proyecto_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_actual', to='projectmanager.proyecto')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='auth.user')),
                ('horasDisponibles', models.FloatField(default=40.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES')], max_length=20)),
                ('horas', models.FloatField(default=0.0)),
                ('totalEnProyecto', models.FloatField(blank=True, null=True)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_de_trabajo', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_de_usuarios', to='projectmanager.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('tiempoEstimadoSMaster', models.FloatField(default=0.0)),
                ('tiempoEstimado', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Cancelado', 'Cancelado'), ('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA'), ('Release', 'Release')], default='Nuevo', max_length=20)),
                ('tiempoEnDesarrollo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prioridad', models.IntegerField(default=1)),
                ('desarrolladorAsignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador_asignado', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='projectmanager.proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_backlog', to='projectmanager.sprint')),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'Users Storys',
                'ordering': ['-prioridad'],
                'permissions': (('desarrollar_user_story', 'Puede desarrollar un user story'),),
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('related_group', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rol', serialize=False, to='auth.group')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('sistema', 'Rol de Sistema'), ('proyecto', 'Rol de Proyecto'), ('defecto', 'Roles por Defecto'), ('proyimp', 'Roles de Proyecto Importados')], default='sistema', max_length=8)),
                ('copied_from', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projectmanager.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'permissions': (('ver_roles', 'Puede ver roles'), ('crear_roles', 'Puede crear roles'), ('actualizar_roles', 'Puede actualizar roles'), ('eliminar_roles', 'Puede eliminar roles'), ('asignar_roles', 'Asigna roles a usuarios'), ('quitar_roles', 'Quita rol de usuarios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RegistroActividadDiairia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=5000)),
                ('hora', models.FloatField(default=0)),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RegistroActividad', to='projectmanager.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(editable=False)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsHistorial', to='projectmanager.userstory')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('version', 'us')},
            },
        ),
    ]
