# Generated by Django 3.2.6 on 2021-08-21 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CAN', 'Cancelado'), ('ACT', 'Activo'), ('FIN', 'Finalizado')], max_length=3)),
                ('product_backlog', models.TextField(blank=True)),
                ('sprintList', models.TextField(blank=True)),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_encargado', to=settings.AUTH_USER_MODEL)),
                ('scrum_member', models.ManyToManyField(related_name='proyecto_asignado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyectos',
                'ordering': ('-fecha_inicio',),
            },
        ),
    ]
