# Generated by Django 3.2.6 on 2021-11-16 16:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorySprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('tiempoEstimadoSMaster', models.FloatField(default=0.0)),
                ('tiempoEstimado', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('no-terminado', 'No Terminado'), ('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA'), ('Release', 'Release')], default='Nuevo', max_length=20)),
                ('tiempoEnDesarrollo', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('prioridad', models.IntegerField(default=1)),
                ('descripcionDone', models.TextField(blank=True, max_length=255)),
                ('desarrolladorAsignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador_asignado_us', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog_us', to='projectmanager.proyecto')),
                ('sprintUs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_backlog_us', to='projectmanager.sprint')),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'Users Storys',
                'ordering': ['estado', '-prioridad'],
                'permissions': (('desarrollar_user_story', 'Puede desarrollar un user story'),),
            },
        ),
    ]
