# Generated by Django 3.2.6 on 2021-09-19 23:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('cancelar_proyecto', 'Puede cancelar un proyecto en estado pendiente'), ('gestionar_scrum_members', 'Puede Agregar/Quitar Scrum Members de un proyecto'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('gestionar_roles_proyecto', 'Puede Agregar/Asignar/Modificar/Eliminar Roles de un Proyecto'), ('importar_roles_proyecto', 'Puede Importar roles de proyecto'), ('gestionar_user_stories', 'Puede Agregar/Modificar/Eliminar User Stories de un proyecto'), ('iniciar_ppoker_proyecto', 'Puede iniciar planning poker de un sprint'), ('estimar_userstory_proyecto', 'Puede estimar User Stories en el Sprint Backlog'), ('cargar_sprint_backlog_proyecto', 'Puede cargar User Stories en el Sprint Backlog')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='userstory',
            name='desarrolladorAsignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEnDesarrollo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='HistorialUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(editable=False)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsHistorial', to='projectmanager.userstory')),
            ],
            options={
                'unique_together': {('version', 'us')},
            },
        ),
    ]
