# Generated by Django 3.2.6 on 2021-09-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('iniciar_proyecto', 'Puede iniciar proyecto')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': (('ver_roles', 'Puede ver roles'), ('crear_roles', 'Puede crear roles'), ('actualizar_roles', 'Puede actualizar roles'), ('eliminar_roles', 'Puede eliminar roles'), ('asignar_roles', 'Asigna roles a usuarios'), ('quitar_roles', 'Quita rol de usuarios')), 'verbose_name_plural': 'Rol'},
        ),
    ]
