# Generated by Django 3.2.6 on 2021-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_finalizacion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
