# Generated by Django 3.2.6 on 2021-09-18 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='auth.user')),
                ('horasDisponibles', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('cancelar_proyecto', 'Puede cancelar un proyecto en estado pendiente'), ('gestionar_scrum_members', 'Puede Agregar/Quitar Scrum Members de un proyecto'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('crear_roles_proyecto', 'Puede Crear Roles de Proyecto'), ('ver_roles_proyecto', 'Puede ver roles de proyecto'), ('modificar_roles_proyecto', 'Puede Modificar Roles de Proyecto'), ('eliminar_roles_proyecto', 'Puede eliminar roles de proyecto'), ('ver_users_storys', 'Puede ver user storys'), ('crear_users_storys', 'Puede crear users storys'), ('actualizar_users_storys', 'Puede actualizar users storys'), ('eliminar_users_storys', 'Puede ver users storys'), ('puede_asignar_users_storys', 'Asigna roles a usuarios'), ('puede_quitar_users_storys', 'Quita users storys de usuarios'), ('gestionar_roles_proyecto', 'Puede Agregar/Asignar/Modificar/Eliminar Roles de un Proyecto'), ('importar_roles_proyecto', 'Puede Importar roles de proyecto'), ('gestionar_user_stories', 'Puede Agregar/Modificar/Eliminar User Stories de un proyecto')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name': 'User Story', 'verbose_name_plural': 'Users Storys'},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='sprintList',
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_sprints', to='projectmanager.proyecto')),
                ('proyecto_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_actual', to='projectmanager.proyecto')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
            },
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sprint', to='projectmanager.sprint'),
        ),
    ]
