# Generated by Django 3.2.6 on 2021-09-12 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('crear_roles_proyecto', 'Puede Crear Roles de Proyecto'), ('ver_roles_proyecto', 'Puede ver roles de proyecto'), ('modificar_roles_proyecto', 'Puede Modificar Roles de Proyecto'), ('eliminar_roles_proyecto', 'Puede eliminar roles de proyecto')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'permissions': (('ver_roles', 'Puede ver roles'), ('crear_roles', 'Puede crear roles'), ('actualizar_roles', 'Puede actualizar roles'), ('eliminar_roles', 'Puede eliminar roles'), ('asignar_roles', 'Asigna roles a usuarios'), ('quitar_roles', 'Quita rol de usuarios')), 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelManagers(
            name='rol',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='product_backlog',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projectmanager.proyecto'),
        ),
        migrations.AddField(
            model_name='rol',
            name='related_group',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rol', serialize=False, to='auth.group'),
        ),
        migrations.AddField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Rol de Sistema'), ('proyecto', 'Rol de Proyecto')], default='sistema', max_length=8),
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=255)),
                ('tiempoEstimado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Cancelado', 'Cancelado'), ('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA'), ('Release', 'Release')], default='Nuevo', max_length=20)),
                ('tiempoEnDesarrollo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('desarrolladorAsignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador_asignado', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='projectmanager.proyecto')),
            ],
        ),
    ]
