# Generated by Django 3.2.6 on 2021-09-10 03:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('iniciar_proyecto', 'Puede iniciar proyecto')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': (('ver_roles', 'Puede ver roles'), ('crear_roles', 'Puede crear roles'), ('actualizar_roles', 'Puede actualizar roles'), ('eliminar_roles', 'Puede eliminar roles'), ('asignar_roles', 'Asigna roles a usuarios'), ('quitar_roles', 'Quita rol de usuarios')), 'verbose_name_plural': 'Rol'},
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=255)),
                ('tiempoEstimado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Cancelado', 'Cancelado'), ('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA'), ('Release', 'Release')], default='Nuevo', max_length=20)),
                ('tiempoEnDesarrollo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('desarrolladorAsignado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador_asignado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
