# Generated by Django 3.2.6 on 2021-11-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividaddiairia',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_us', to='projectmanager.sprint'),
        ),
    ]
