# Generated by Django 3.2.6 on 2021-09-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20210913_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('crear_roles_proyecto', 'Puede Crear Roles de Proyecto'), ('ver_roles_proyecto', 'Puede ver roles de proyecto'), ('modificar_roles_proyecto', 'Puede Modificar Roles de Proyecto'), ('eliminar_roles_proyecto', 'Puede eliminar roles de proyecto'), ('ver_users_storys', 'Puede ver user storys'), ('crear_users_storys', 'Puede crear users storys'), ('actualizar_users_storys', 'Puede actualizar users storys'), ('eliminar_users_storys', 'Puede ver users storys'), ('puede_asignar_users_storys', 'Asigna roles a usuarios'), ('puede_quitar_users_storys', 'Quita users storys de usuarios')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name_plural': 'Users Storys'},
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fechaInicio', models.DateTimeField()),
                ('duracionEstimada', models.IntegerField()),
                ('fechaFinalización', models.DateTimeField()),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='projectmanager.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sprint', to='projectmanager.sprint'),
        ),
    ]
