# Generated by Django 3.2.6 on 2021-09-18 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20210917_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_backlog', to='projectmanager.sprint'),
        ),
    ]
