# Generated by Django 3.2.6 on 2021-08-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_alter_proyecto_fecha_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('can_access', 'Puede acceder a la pagina'),), 'verbose_name': 'Proyectos'},
        ),
    ]
