# Generated by Django 3.2.6 on 2021-09-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20210903_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': (('ver_roles', 'Puede ver roles'), ('crear_roles', 'Puede crear roles'), ('actualizar_roles', 'Puede actualizar roles'), ('eliminar_roles', 'Puede eliminar roles'), ('asignar_roles', 'Asigna roles a usuarios'), ('quitar_roles', 'Quita rol de usuarios'), ('crear_roles_proyecto', 'Puede Crear Roles de Proyecto'), ('ver_roles_proyecto', 'Puede ver roles de proyecto'), ('modificar_roles_proyecto', 'Puede Modificar Roles de Proyecto'), ('eliminar_roles_proyecto', 'Puede eliminar roles de proyecto')), 'verbose_name_plural': 'Rol'},
        ),
    ]
