# Generated by Django 3.2.6 on 2021-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_registroactividaddiairia_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='tiempoEnDesarrolloPrevio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
