# Generated by Django 3.2.6 on 2021-11-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_sprint_fecha_finalizacion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='proyecto_sig',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siguiente_sprint', to='projectmanager.proyecto'),
        ),
    ]
