# Generated by Django 3.2.6 on 2021-10-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_alter_proyecto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(max_length=255)),
                ('aceptar', models.BooleanField(default=False)),
                ('user_story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='QA', to='projectmanager.userstory')),
            ],
        ),
    ]
