# Generated by Django 3.2.6 on 2021-09-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20210915_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='duracionEstimada',
            new_name='duracion_estimada',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='fechaFinalización',
            new_name='fecha_finalización',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
    ]
