# Generated by Django 3.2.6 on 2021-09-18 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_userstory_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='nombre',
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
