# Generated by Django 3.2.6 on 2021-10-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
