# Generated by Django 3.2.6 on 2021-09-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_userstory_desarrolladorasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_story', to='projectmanager.proyecto'),
        ),
    ]
