# Generated by Django 3.2.6 on 2021-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_sprint_proyecto_sig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacidad_horas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
