# Generated by Django 3.2.6 on 2021-09-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('gestionar_scrum_members', 'Puede Agregar/Quitar Scrum Members de un proyecto'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('gestionar_roles_proyecto', 'Puede Agregar/Asignar/Modificar/Eliminar Roles de un Proyecto'), ('importar_roles_proyecto', 'Puede Importar roles de proyecto'), ('gestionar_user_stories', 'Puede Agregar/Modificar/Eliminar User Stories de un proyecto')), 'verbose_name': 'Proyectos'},
        ),
    ]
