# Generated by Django 3.2.6 on 2021-09-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_userworktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworktime',
            name='totalEnProyecto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
