# Generated by Django 3.2.6 on 2021-10-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='descripcion_done',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
