# Generated by Django 3.2.6 on 2021-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_historialus_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividaddiairia',
            name='hora',
            field=models.FloatField(default=0),
        ),
    ]
