# Generated by Django 3.2.6 on 2021-10-07 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_alter_registroactividaddiairia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEnDesarrollo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
