# Generated by Django 3.2.6 on 2021-09-18 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20210918_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['-prioridad'], 'verbose_name': 'User Story', 'verbose_name_plural': 'Users Storys'},
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
