# Generated by Django 3.2.6 on 2021-10-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_userstory_descripcion_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='descripcion_done',
            new_name='descripcionDone',
        ),
    ]
