# Generated by Django 3.2.6 on 2021-09-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20210915_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duracion_estimada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_finalización',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
