# Generated by Django 3.2.6 on 2021-09-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectmanager', '0004_auto_20210910_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'permissions': (
            ('ver_roles', 'Puede ver roles'), ('crear_roles', 'Puede crear roles'),
            ('actualizar_roles', 'Puede actualizar roles'), ('eliminar_roles', 'Puede eliminar roles'),
            ('asignar_roles', 'Asigna roles a usuarios'), ('quitar_roles', 'Quita rol de usuarios')),
                     'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelManagers(
            name='rol',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='rol',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='roles', to='projectmanager.proyecto'),
        ),
        migrations.AddField(
            model_name='rol',
            name='related_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                       related_name='rol', serialize=False, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Rol de Sistema'), ('proyecto', 'Rol de Proyecto')],
                                   default='sistema', max_length=8),
        ),
    ]
