# Generated by Django 3.2.6 on 2021-11-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_sprint_capacidad_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='horas_ocupadas_us',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacidad_horas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
