# Generated by Django 3.2.6 on 2021-10-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20211004_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_inicio_desarrollo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
