# Generated by Django 3.2.6 on 2021-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_alter_qa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='duracion_restante_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
