# Generated by Django 3.2.6 on 2021-08-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('can_access', 'Puede acceder a la pagina'), ('can_create', 'Puede crear un proyecto'), ('can_autorize_user', 'Puede Autorizar un usuario')), 'verbose_name': 'Proyectos'},
        ),
    ]
