# Generated by Django 3.2.6 on 2021-09-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_userstory_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='proyecto',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='product_backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='projectmanager.userstory'),
        ),
    ]
