# Generated by Django 3.2.6 on 2021-08-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('can_create', 'Puede crear un proyecto'),), 'verbose_name': 'Proyectos'},
        ),
    ]
