# Generated by Django 3.2.6 on 2021-10-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_rename_descripcion_done_userstory_descripciondone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialus',
            name='descripcionDone',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcionDone',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
