# Generated by Django 3.2.6 on 2021-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_sprint_fecha_inicio_desarrollo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='horas_realizadas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
