# Generated by Django 3.2.6 on 2021-09-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_auto_20210910_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='product_backlog',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='product_backlog',
            field=models.ManyToManyField(related_name='product_backlog', to='projectmanager.UserStory'),
        ),
    ]
