# Generated by Django 3.2.6 on 2021-09-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectmanager', '0005_alter_proyecto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='auth.user')),
                ('horasDisponibles', models.PositiveIntegerField(default=40)),
            ],
        ),
    ]
