# Generated by Django 3.2.6 on 2021-09-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_auto_20210911_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Rol de Sistema'), ('proyecto', 'Rol de Proyecto'), ('defecto', 'Roles por Defecto')], default='sistema', max_length=8),
        ),
    ]
