# Generated by Django 3.2.6 on 2021-10-07 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_alter_userstory_tiempoendesarrollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_finalizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
