# Generated by Django 3.2.6 on 2021-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_sprint_duracion_restante_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialus',
            name='descripcionDone',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userstory',
            name='descripcionDone',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
