# Generated by Django 3.2.6 on 2021-08-26 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0006_alter_proyecto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.ManyToManyField(related_name='Lista_Usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
