# Generated by Django 3.2.6 on 2021-09-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name_plural': 'Users Storys'},
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('fecha_finalización', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='projectmanager.proyecto')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
            },
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sprint', to='projectmanager.sprint'),
        ),
    ]
