# Generated by Django 3.2.6 on 2021-11-16 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_userstory_saldo_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividaddiairia',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 20, 1, 55, 710517, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='registroactividaddiairia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
