# Generated by Django 3.2.6 on 2021-09-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20210912_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Rol de Sistema'), ('proyecto', 'Rol de Proyecto'), ('defecto', 'Roles por Defecto'), ('proyimp', 'Roles de Proyecto Importados')], default='sistema', max_length=8),
        ),
    ]
