# Generated by Django 3.2.6 on 2021-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20210915_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'verbose_name': 'User Story', 'verbose_name_plural': 'Users Storys'},
        ),
        migrations.AlterField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
