# Generated by Django 3.2.6 on 2021-09-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20210910_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='product_backlog',
        ),
        migrations.AddField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='projectmanager.proyecto'),
        ),
    ]
