# Generated by Django 3.2.6 on 2021-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_alter_rol_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='copied_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
