# Generated by Django 3.2.6 on 2021-08-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
