# Generated by Django 3.2.6 on 2021-10-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_loghistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('conf1', 'Carga de Sprint Backlog'), ('conf2', 'Planning Poker'), ('conf3', 'Sprint en desarrollo'), ('fin', 'Sprint finalizado')], default='conf1', max_length=20),
        ),
    ]
