# Generated by Django 3.2.6 on 2021-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_loghistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialus',
            name='idUs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='historialus',
            name='prioridad',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
