# Generated by Django 3.2.6 on 2021-09-01 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0007_auto_20210826_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto')), 'verbose_name': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='scrum_member',
            field=models.ManyToManyField(blank=True, related_name='proyecto_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
