# Generated by Django 3.2.6 on 2021-09-17 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_auto_20210917_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='fecha_finalización',
            new_name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='nombre',
        ),
        migrations.AddField(
            model_name='sprint',
            name='proyecto_actual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_actual', to='projectmanager.proyecto'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_sprints', to='projectmanager.proyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_backlog', to='projectmanager.sprint'),
        ),
    ]
