# Generated by Django 3.2.6 on 2021-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_auto_20210901_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('CAN', 'Cancelado'), ('ACT', 'Activo'), ('FIN', 'Finalizado')], default='PEN', max_length=3),
        ),
    ]
