# Generated by Django 3.2.6 on 2021-09-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_alter_userstory_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
    ]
