# Generated by Django 3.2.6 on 2021-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_alter_sprint_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
