# Generated by Django 3.2.6 on 2021-09-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_rol_copied_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'default_permissions': (), 'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('iniciar_proyecto', 'Puede iniciar proyecto'), ('crear_roles_proyecto', 'Puede Crear Roles de Proyecto'), ('ver_roles_proyecto', 'Puede ver roles de proyecto'), ('modificar_roles_proyecto', 'Puede Modificar Roles de Proyecto'), ('eliminar_roles_proyecto', 'Puede eliminar roles de proyecto'), ('importar_roles_proyecto', 'Puede Importar roles de proyecto')), 'verbose_name': 'Proyectos'},
        ),
    ]
