# Generated by Django 3.2.6 on 2021-09-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0009_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyectos', 'Puede ver proyectos')), 'verbose_name': 'Proyectos'},
        ),
    ]
