# Generated by Django 3.2.6 on 2021-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0009_alter_userstory_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(editable=False)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('version', 'descripcion')},
            },
        ),
    ]
