# Generated by Django 3.2.6 on 2021-08-27 07:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0009_merge_0006_auto_20210827_0503_0008_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='scrum_member',
            field=models.ManyToManyField(related_name='proyecto_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'ordering': ['name'],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
