# Generated by Django 3.2.6 on 2021-09-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_alter_proyecto_options'),
        ('projectmanager', '0010_auto_20210827_0733'),
    ]

    operations = [
    ]
