# Generated by Django 3.2.6 on 2021-09-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos')), 'verbose_name': 'Proyectos'},
        ),
    ]
