# Generated by Django 3.2.6 on 2021-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_alter_proyecto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='tiempoEstimadoSMaster',
            field=models.IntegerField(default=0),
        ),
    ]
