# Generated by Django 3.2.6 on 2021-09-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_historialus'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialus',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.userstory'),
        ),
    ]
