# Generated by Django 3.2.6 on 2021-10-27 19:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0010_alter_userstory_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['estado', '-prioridad'], 'permissions': (('desarrollar_user_story', 'Puede desarrollar un user story'),), 'verbose_name': 'User Story', 'verbose_name_plural': 'Users Storys'},
        ),
        migrations.AddField(
            model_name='sprint',
            name='saved_us_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='desarrolladorAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
