# Generated by Django 3.2.6 on 2021-11-17 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0010_alter_proyecto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadSMasteSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_horas', models.FloatField(blank=True, default=0, null=True)),
                ('saldo_horas', models.FloatField(blank=True, default=models.FloatField(blank=True, default=0, null=True), null=True)),
                ('scrum_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidad_sprints', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidad_de_smembers', to='projectmanager.sprint')),
            ],
        ),
    ]
