# Generated by Django 3.2.6 on 2021-09-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_historialus_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialus',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsHisorial', to='projectmanager.userstory'),
        ),
        migrations.AlterUniqueTogether(
            name='historialus',
            unique_together={('version', 'us')},
        ),
    ]
