# Generated by Django 3.2.6 on 2021-10-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_auto_20211027_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='saved_horas_us_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
