# Generated by Django 3.2.6 on 2021-09-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_merge_20210902_0434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['name'], 'verbose_name_plural': 'Rol'},
        ),
    ]
