# Generated by Django 3.2.6 on 2021-09-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_alter_sprint_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
    ]
