# Generated by Django 3.2.6 on 2021-09-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
