# Generated by Django 3.2.6 on 2021-09-18 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_userstory_tiempoestimadosmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duracion_estimada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='horasDisponibles',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEnDesarrollo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEstimado',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEstimadoSMaster',
            field=models.FloatField(default=0.0),
        ),
    ]
