# Generated by Django 3.2.6 on 2021-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_auto_20211117_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividaddiairia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
