# Generated by Django 3.2.6 on 2021-09-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_alter_rol_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='usuario',
        ),
    ]
