# Generated by Django 3.2.6 on 2021-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
