# Generated by Django 3.2.6 on 2021-09-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_auto_20210919_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialus',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsHistorial', to='projectmanager.userstory'),
        ),
    ]
