# Generated by Django 3.2.6 on 2021-09-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_remove_rol_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['name'], 'permissions': (('ver_roles', 'Puede ver roles'),), 'verbose_name_plural': 'Rol'},
        ),
    ]
