# Generated by Django 3.2.6 on 2021-10-27 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_alter_userstory_tiempoendesarrollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tiempoEstimado',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
