# Generated by Django 3.2.6 on 2021-11-17 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_alter_registroactividaddiairia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registroactividaddiairia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
