# Generated by Django 3.2.6 on 2021-09-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_alter_proyecto_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('-fecha_inicio',), 'permissions': (('crear_proyecto', 'Puede crear un proyecto'), ('editar_proyecto', 'Puede editar un proyecto'), ('ver_proyecto', 'Puede ver un proyecto en detalle'), ('ver_proyectos', 'Puede ver proyectos'), ('iniciar_proyecto', 'Puede iniciar proyecto')), 'verbose_name': 'Proyectos'},
        ),
    ]
