# Generated by Django 3.2.6 on 2021-11-17 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0014_auto_20211117_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='saved_act_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
