# Generated by Django 3.2.6 on 2021-09-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0014_alter_userstory_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sprint', to='projectmanager.sprint'),
        ),
    ]
