# Generated by Django 3.2.6 on 2021-09-16 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0016_alter_userstory_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='desarrollador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desarrollador', to=settings.AUTH_USER_MODEL),
        ),
    ]
