# Generated by Django 3.2.6 on 2021-11-17 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0016_sprint_scrum_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='scrum_member',
            field=models.ManyToManyField(blank=True, related_name='sprints', to=settings.AUTH_USER_MODEL),
        ),
    ]
