# Generated by Django 3.2.6 on 2021-09-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0017_userstory_desarrollador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='desarrollador',
        ),
    ]
