# Generated by Django 3.2.6 on 2021-09-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0018_remove_userstory_desarrollador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
