# Generated by Django 3.2.6 on 2021-09-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0020_auto_20210917_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
